Resources:
  bioetanolTotal:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: bioetanol_total
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: N
        - AttributeName: produccion
          AttributeType: N
        - AttributeName: ventas_totales
          AttributeType: N  
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1