Resources:
  bioetanolTotal:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: bioetanol_total
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: produccion
          AttributeType: N
        - AttributeName: ventas_totales
          AttributeType: N  
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: produccion
          KeyType: RANGE
        - AttributeName: ventas_totales
          KeyType: RANGE   
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5