Resources:
  bioetanolTotal:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: bioetanolTotal
      AttributeDefinitions:
        - AttributeName: periodo
          AttributeType: S
        - AttributeName: title
          AttributeType: S
      KeySchema:
        - AttributeName: year
          KeyType: HASH
        - AttributeName: title
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 10
        WriteCapacityUnits: 10